### ISSUE TITLE
Document DOCKER_SOCK_FILE

### ISSUE THREAD

**Issue by sebinievas** [micalexander/docker-dev#1]
I get the following when running `docker-compose up` for the first time after setting up `.env` from the `README` defaults.

The following warning appears:

`WARNING: The DOCKER_SOCK_FILE variable is not set. Defaulting to a blank string.`

**Comment by wizalexander** [comment]
Updated readme to have these lines in the .env file

```
# Points to the docker sock file
DOCKER_SOCK_FILE=/var/run/docker.sock
```
